name: Nightly

on:
  schedule:
    - cron:  "0 0 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Upload keystore
        shell: bash
        run: echo ${NIGHTLY_STORE_FILE} | base64 -d > KEY_NIGHTLY.jks
        env:
          NIGHTLY_STORE_FILE: ${{ secrets.NIGHTLY_STORE_FILE }}
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Sign the build
        run: jarsigner -keystore KEY_NIGHTLY.jks --storepass ${NIGHTLY_STORE_PASSWORD} -keypass ${NIGHTLY_STORE_PASSWORD} ./app/build/outputs/apk/debug/app-debug.apk ${NIGHTLY_KEY_ALIAS}
        env:
          NIGHTLY_STORE_PASSWORD: ${{ secrets.NIGHTLY_STORE_PASSWORD }}
          NIGHTLY_KEY_ALIAS: ${{ secrets.NIGHTLY_KEY_ALIAS }
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: Heart-Rate-Nightly.apk
          path: ./app/build/outputs/apk/debug/app-debug.apk
          retention-days: 7
