name: Nightly

on:
  schedule:
    - cron:  "0 0 * * *"
  workflow_dispatch:
    inputs:
      force:
        description: 'Force a nightly build, even if there are no changes'
        required: false
        type: boolean

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # From https://github.com/nvim-neorocks/luarocks-tag-release#version-optional
      - name: Check for changes
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: Setup Java
        if: ${{ inputs.force || env.NEW_COMMIT_COUNT > 0 }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Make gradlew executable
        if: ${{ inputs.force || env.NEW_COMMIT_COUNT > 0 }}
        run: chmod +x ./gradlew
      - name: Build APK
        if: ${{ inputs.force || env.NEW_COMMIT_COUNT > 0 }}
        run: |
          echo ${NIGHTLY_STORE_FILE} | base64 -d > KEY_NIGHTLY.jks
          ./gradlew assembleNightly -Dnightly_store_file=../KEY_NIGHTLY.jks -Dnightly_store_password="${NIGHTLY_STORE_PASSWORD}" -Dnightly_key_alias="${NIGHTLY_KEY_ALIAS}" -Dnightly_key_password="${NIGHTLY_STORE_PASSWORD}"
        env:
          NIGHTLY_STORE_PASSWORD: ${{ secrets.NIGHTLY_STORE_PASSWORD }}
          NIGHTLY_KEY_ALIAS: ${{ secrets.NIGHTLY_KEY_ALIAS }}
          NIGHTLY_STORE_FILE: ${{ secrets.NIGHTLY_STORE_FILE }}
      - name: Archive
        if: ${{ inputs.force || env.NEW_COMMIT_COUNT > 0 }}
        uses: actions/upload-artifact@v3
        with:
          name: Heart-Rate-Nightly.apk
          path: ./app/build/outputs/apk/nightly/*.apk
          retention-days: 7
